modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="lolocraft"
version="1.2.0"
displayName="LoloCraftVIII"
credits="The LoloCraftV3 Mod for Minecraft 1.16.5"
displayURL="https://mclolocraft.jimdosite.com"
authors="DerLoloHD"
description='''
The LoloCraft Mod Remake for Minecraft 1.16.5
'''

[[dependencies.lolocraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




